spring:
    datasource:
        url: jdbc:mysql://localhost:3306/fxbot_dev
        username: fxbot_dev_user
        password: F*angXiaDe*v
        driver-class-name: com.mysql.cj.jdbc.Driver

    quartz:
        scheduler-name: fxbotSchedulerDev
        job-store-type: jdbc
        jdbc:
            initialize-schema: always
        properties:
            org:
                quartz:
                    jobStore:
                        isClustered: false
                        tablePrefix: QRTZ_
                    threadPool:
                        threadCount: 5

mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.fangxia.fxbot.eo, com.fangxia.fxbot.dto, com.fangxia.fxbot.vo

logging:
    level:
        root: DEBUG
        com.fangxia.fxbot: DEBUG
    pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n"
