USE fxbot_dev;

CREATE TABLE fx_users (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    discord_id BIGINT NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
